## Arithmetic among Matrices

In [18]:
import numpy as np

matA = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

matB = np.array([[1, 3, 5, 7],
                 [2, 4, 6, 8]])

matC = np.array([[1, -2],
                 [-3, 4],
                 [5, -6],
                 [-7, 8]])
print("Matrix Addition:")
print("", matA, "\n + \n", matB, "\n = \n", np.add(matA, matB))
print()

print("Matrix Subtraction:")
print("", matA, "\n - \n", matB, "\n = \n", np.subtract(matA, matB))
print()

print("Matrix Multiplication:")
print("", matA, "\n - \n", matC, "\n = \n", np.matmul(matA, matC))

Matrix Addition:
 [[1 2 3 4]
 [5 6 7 8]] 
 + 
 [[1 3 5 7]
 [2 4 6 8]] 
 = 
 [[ 2  5  8 11]
 [ 7 10 13 16]]

Matrix Subtraction:
 [[1 2 3 4]
 [5 6 7 8]] 
 - 
 [[1 3 5 7]
 [2 4 6 8]] 
 = 
 [[ 0 -1 -2 -3]
 [ 3  2  1  0]]

Matrix Multiplication:
 [[1 2 3 4]
 [5 6 7 8]] 
 - 
 [[ 1 -2]
 [-3  4]
 [ 5 -6]
 [-7  8]] 
 = 
 [[-18  20]
 [-34  36]]
