## Determinant of a Square matrix

In [3]:
import numpy as np

sqr_matrix = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print("Given square matrix:\n", sqr_matrix)
print("Determinant of the matrix is ", np.linalg.det(sqr_matrix))
print()

identity_matrix = np.array([[1, 0, 0],
                           [0, 1, 0],
                           [0, 0, 1]])

print("Identity matrix:\n", identity_matrix)
print("Determinant of the identity matrix is ", np.linalg.det(identity_matrix))

Given square matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of the matrix is  -9.51619735392994e-16

Identity matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Determinant of the identity matrix is  1.0
