## Inverse of Matrix

In [2]:
import numpy as np

sqr_matrix = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
identity_matrix = np.array([[1, 0, 0],
                            [0, 1, 0],
                            [0, 0, 1]])

print("Square matrix:\n", sqr_matrix)
print("Inverse of square matrix:\n", np.linalg.inv(sqr_matrix))
print()

print("Identity matrix:\n", identity_matrix)
print("Inverse of the identity matrix:\n", np.linalg.inv(identity_matrix))

Square matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Inverse of square matrix:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]

Identity matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Inverse of the identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
