## Min, Max elements from an Array

In [18]:
import numpy as np

rect_matrix = np.array([[1, 6, 7, 4],
                        [5, 2, 3, 8]])

print("Largest element of the matrix = ", np.max(rect_matrix))
print("Smallest element of the matrix = ", np.min(rect_matrix))
print()

print("Largest element(s) in each column:")
print(np.max(rect_matrix, axis=0))
print("Largest element(s) in each row:")
print(np.max(rect_matrix, axis=1))
print()

print("Smallest element(s) in each column:")
print(np.min(rect_matrix, axis=0))
print("Smallest element(s) in each row:")
print(np.min(rect_matrix, axis=1))
print()

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Largest element(s) in each column:")
print(np.max(matrix, axis=0))
print("Largest element(s) in each row:")
print(np.max(matrix, axis=1))

Largest element of the matrix =  8
Smallest element of the matrix =  1

Largest element(s) in each column:
[5 6 7 8]
Largest element(s) in each row:
[7 8]

Smallest element(s) in each column:
[1 2 3 4]
Smallest element(s) in each row:
[1 2]

Largest element(s) in each column:
[7 8 9]
Largest element(s) in each row:
[3 6 9]
