## Sparse Matrix

In [19]:
import numpy as np
from scipy.sparse import bsr_matrix

print("There are several types of sparse matrices:")
print("spmatrix - Base matrix of all sparse matrices")
print("1) bsr_matrix - Block Sparse Row")
print("2) coo_matrix - Sparse matrix in COOrdiante format")
print("3) csr_matrix - Compressed Sparse Row matrix")
print("4) csc_matrix - Compressed Sparse Column matrix")
print("5) dia_matrix - Sparse matrix with DIAgonal storage")
print("6) dok_matrix - Dictionary Of Keys based sparse matrix")
print("7) lil_matrix - Row based LInked List sparse matrix")

There are several types of sparse matrices:
spmatrix - Base matrix of all sparse matrices
1) bsr_matrix - Block Sparse Row
2) coo_matrix - Sparse matrix in COOrdiante format
3) csr_matrix - Compressed Sparse Row matrix
4) csc_matrix - Compressed Sparse Column matrix
5) dia_matrix - Sparse matrix with DIAgonal storage
6) dok_matrix - Dictionary Of Keys based sparse matrix
7) lil_matrix - Row based LInked List sparse matrix


In [20]:
sparse_mat = np.array([[0, 0, 0, 1],
                          [2, 0, 0, -1],
                          [0, 0, 3, 0],
                          [0, 0, 0, -5]])

# Convert sparse matrix to bsr matrix
sparse_bsr = sparse.bsr_matrix(sparse_mat)
print(sparse_bsr)

  (0, 3)	1
  (1, 0)	2
  (1, 3)	-1
  (2, 2)	3
  (3, 3)	-5


In [21]:
# Creation of a BSR sparse matrix (Note: we don't mention the indices of data value 0)
row_indx = np.array([0, 0, 1, 2, 2, 2])
col_indx = np.array([0, 2, 2, 0, 1, 2])
data     = np.array([1, 2, 3, 4, 5, 6])

sparse_bsr = bsr_matrix((data, (row_indx, col_indx)), shape=(3, 3)).toarray()
print("bsr sparse matrix:\n", sparse_bsr)

bsr sparse matrix:
 [[1 0 2]
 [0 0 3]
 [4 5 6]]
