## Trace Of Matrix

In [5]:
import numpy as np

square_matrix = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

print("Square matrix:\n", square_matrix)
print("Diagonal vector of the matrix:\n", square_matrix.diagonal())
print()

rect_matrix = np.array([[1, 2, 3, 4],
                        [5, 6, 7, 8]])
print("Rectangular matrix:\n", rect_matrix)
print("Diagonal vector of the rectangular matrix:\n", rect_matrix.diagonal())

print("\nThe trace of a matrix is defined only for a 'square matrix' and it is the sum of all main diagonal elements")
print("The trace of the square matrix is ", square_matrix.diagonal().sum())

Square matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal vector of the matrix:
 [1 5 9]

Rectangular matrix:
 [[1 2 3 4]
 [5 6 7 8]]
Diagonal vector of the rectangular matrix:
 [1 6]

The trace of a matrix is defined only for a 'square matrix' and it is the sum of all main diagonal elements
The trace of the square matrix is  15
