## Transpose A Vector Or Matrix

In [24]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
rect_matrix = np.array([[1, 2, 3, 4],
                   [4, 5, 6, 8]])
sqr_matrix = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print("Sizes before transpose:")
print("-----------------------")

print(vector)
print("Size of the vector = ", vector.shape)
print()

print(rect_matrix)
print("Size of the rectangle matrix = ", rect_matrix.shape)
print()

print(sqr_matrix)
print("Size of the square matrix = ", sqr_matrix.shape)
print()

tr_vector = vector.T
tr_rect_matrix = rect_matrix.T
tr_sqr_matrix = sqr_matrix.T

print("Sizes after transpose:")
print("----------------------")

print(tr_vector)
print("Size of the vector = ", tr_vector.shape)
print()

print("Size of the Rectangle vector = ", tr_rect_matrix.shape)
print(tr_rect_matrix)
print()

print("Size of the Square matrix = ", tr_sqr_matrix.shape)
print(tr_sqr_matrix)

Sizes before transpose:
-----------------------
[1 2 3 4 5 6 7 8 9]
Size of the vector =  (9,)

[[1 2 3 4]
 [4 5 6 8]]
Size of the rectangle matrix =  (2, 4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Size of the square matrix =  (3, 3)

Sizes after transpose:
----------------------
[1 2 3 4 5 6 7 8 9]
Size of the vector =  (9,)

Size of the Rectangle vector =  (4, 2)
[[1 4]
 [2 5]
 [3 6]
 [4 8]]

Size of the Square matrix =  (3, 3)
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1], [2], [3], [4]]


AttributeError: 'list' object has no attribute 'shape'