In [2]:
# Following program declares Numpy arrays and demonstrates attributes
# Attributes
#  ndim - number of dimensions
#  shape - size of each dimension
#  size - total size of array
#  dtype - data type of the array
#  itemsize - size in bytes of each element in array
#  nbytes   - size in bytes of all elements in array

import numpy as np

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5))

print("x3 dimensions = ", x3.ndim)
print("x3 size of each dimension = ", x3.shape)
print("x3 total size of array = ", x3.size)
print("x3 array type = ", x3.dtype)
print("x3 size in bytes of each element = ", x3.itemsize)
print("x3 size in bytes of entire array = ", x3.nbytes)


x3 dimensions =  3
x3 size of each dimension =  (3, 4, 5)
x3 total size of array =  60
x3 array type =  int32
x3 size in bytes of each element =  4
x3 size in bytes of entire array =  240


In [98]:
# Accessing elements of single dimensional array
print("First element of x1 = ", x1[0])
print("Second element of x1 = ", x1[1])

print("First element of x1 from end of the array = ", x1[-1])
print("Second eleme1t 2f 31 from end1of2th3 array = ", x1[-2])

# Accessing elements of two dimensional array
print("Element at (0, 0) = ", x2[0, 0])
print("Element at (1, 1) = ", x2[1, 1])
print("Element at (2, 3) = ", x2[2, 3])

# Accessing elements of three dimensional array
print("Element at (0, 0, 0) = ", x3[0, 0, 0])
print("Element at (1, 2, 3) = ", x3[1, 2, 3])



First element of x1 =  2
Second element of x1 =  7
First element of x1 from end of the array =  2
Second eleme1t 2f 31 from end1of2th3 array =  0
Element at (0, 0) =  2
Element at (1, 1) =  1
Element at (2, 3) =  5
Element at (0, 0, 0) =  0
Element at (1, 2, 3) =  9


In [99]:
# Slicing - x[start:stop:step]
# defalut values are
#  start = 0
#  stop = size of dimension
#  step = 1
x4 = np.arange(10)

print("Extract partial elements from the array:")
print(x4[3:7:1])
print(x4[5:])
print(x4[:5])

print("Extract partial elements of the array from beginning:")
print(x4[::1])
print(x4[::2])
print(x4[::3])
print(x4[::4])
print(x4[::5])
print(x4[::6])

print("Extract elements of the array from end:")
print(x4[::-1])
print(x4[::-2])
print(x4[::-3])
print(x4[::-4])
print(x4[::-5])
print(x4[::-6])


Extract partial elements from the array:
[3 4 5 6]
[5 6 7 8 9]
[0 1 2 3 4]
Extract partial elements of the array from beginning:
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]
[0 4 8]
[0 5]
[0 6]
Extract elements of the array from end:
[9 8 7 6 5 4 3 2 1 0]
[9 7 5 3 1]
[9 6 3 0]
[9 5 1]
[9 4]
[9 3]


In [100]:
x5 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
x5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
# Get a row
x5[:1]

array([[1, 2, 3, 4]])

In [102]:
# Get two rows
x5[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
# Get three rows
x5[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
# Get a column
x5[:, :1]

array([[1],
       [5],
       [9]])

In [105]:
# Get two columns
x5[:, :2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [106]:
# Get three columns
x5[:, :3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [107]:
# Get four columns
x5[:, :4]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
# Get columns indexed as 1, 2
x5[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [109]:
# Get specific column, for example third column
x5[:, 2]

array([ 3,  7, 11])

In [110]:
# Get specific row, for example second row
print(x5[1, :])
print(x5[1]) # column specifier can be ommitted

[5 6 7 8]
[5 6 7 8]


In [111]:
# Get rows indexed as 1, 2 and columns indexed as 1, 2
x5[1:2, 1:3]

array([[6, 7]])

In [112]:
# Reversing rows and columns
x5[::-1, ::-1]

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [113]:
# Numpy array slices are views of the original array (not copies); Python lists will give copies
# Demo to show that modification to the view reflects changes in the original too as it is the view of the original
x5_sub = x5[:2,:2]
print("sub array of x5:")
print(x5_sub)
# Modify an element of the sub array
x5_sub[0, 0] = 99
print("sub array after modification:")
print(x5_sub)
print("x5 (reflects modification to sub array in orginal array):")
print(x5)

sub array of x5:
[[1 2]
 [5 6]]
sub array after modification:
[[99  2]
 [ 5  6]]
x5 (reflects modification to sub array in orginal array):
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [114]:
# Numpy array slices are views but you can get copies also
x5_sub_copy = x5[:2, :2].copy()
print("x5_sub_copy:")
print(x5_sub_copy)
# Any modification to this sub array will not reflect in the original as it is a copy
print("x5_sub_copy (after modification):")
x5_sub_copy[0, 0] = -1
print(x5_sub_copy)
print("x5:")
print(x5)

x5_sub_copy:
[[99  2]
 [ 5  6]]
x5_sub_copy (after modification):
[[-1  2]
 [ 5  6]]
x5:
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [115]:
# Reshaping of arrays with reshape or newaxis
grid = np.arange(1, 13)
print("an array:")
print(grid)
grid = grid.reshape((3, 4))
print("Reshapped grid:")
print(grid)

an array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshapped grid:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [116]:
# Reshaping an array to a row vector
r = np.array([1, 2, 3])
r.reshape((1, 3))

array([[1, 2, 3]])

In [117]:
# Reshaping an array to a column vector
r = np.array([1, 2, 3])
r.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [118]:
# Concatenation of multiple arrays (single dimension)
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])
xy = np.concatenate([x, y])
print(xy)
xyz = np.concatenate([x, y, z])
print(xyz)

[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8 9]


In [119]:
# Concatenation of multiple arrays (two dimension)
g1 = np.array([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
g2 = np.array([[11, 22, 33, 44],
               [55, 66, 77, 88]])

# concatenate along the first axis
g12 = np.concatenate([g1, g2]) # axis = 0 (optional argument)
print(g12)

# concatenate along the second axis (zero indexed)
g12dash = np.concatenate([g1, g2], axis = 1)
print(g12dash)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]
 [55 66 77 88]]
[[ 1  2  3  4 11 22 33 44]
 [ 5  6  7  8 55 66 77 88]]


In [120]:
# Concatenate using vstack
r = np.array([1, 2, 3])
grid = np.array([[4, 5, 6],
                 [7, 8, 9]])
v = np.vstack([r, grid])
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [121]:
# Concatenate using hstack
v = np.array([[11],
              [22]])
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
h = np.hstack([grid, v])
print(h)

[[ 1  2  3 11]
 [ 4  5  6 22]]


In [122]:
# Split
# numpy.split(ary, indices_or_sections, axis=0)
# For example, [2, 3] would, for axis=0, result in
#     ary[:2]
#     ary[2:3]
#     ary[3:]
# n splits results in n+1 subarrays
# If an index exceeds the dimension of the array along axis, an empty sub-array is returned correspondingly.

x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3, x4 = np.split(x, [1, 3, 5])
print(x1)
print(x2)
print(x3)
print(x4)

[1]
[2 3]
[4 5]
[6 7 8 9]


In [123]:
# Vertical split
grid = np.arange(16).reshape(4, 4)
grid
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)
u1, l1 = np.vsplit(grid, [3])
print(u1)
print(l1)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [124]:
# Horizontal split
grid = np.arange(16).reshape(4, 4)
grid
left, right = np.hsplit(grid, [2])
print(left)
print(right)
l1, r1 = np.hsplit(grid, [3])
print(l1)
print(r1)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]


In [125]:
# Demonstrate default implementation of Python's operations can be slow and the need for Numpy's ufuncs
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
%timeit compute_reciprocals(values)

12.8 µs ± 772 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [126]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(values)

11.9 µs ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [127]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.25       0.25       0.125      0.33333333 0.2       ]
[0.25       0.25       0.125      0.33333333 0.2       ]


In [128]:
%timeit (1.0 / big_array)

8.66 ms ± 268 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [129]:
# Numpy's UFuncs
x = np.arange(10)
print("x = ", x)
print("x + 5 = ", x+5)
print("x - 5 = ", x-5)
print("x * 2 = ", x*2)
print("x / 2 = ", x/2)
print("x // 2 = ", x//2)
print("-x =", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)
print("-((0.5 * x + 1) ** 2)) = ", -((0.5 * x + 1) ** 2))
print("x.add(2) = ", np.add(x, 2))
xabs = np.array([-2, -1, 0, 1, 2])
print("abs(xabs) = ", np.abs(xabs))
# abs function of numpy for complex numbers calculates the magnitude
cmplx = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print("Magnitudes are ", np.abs(cmplx))

x =  [0 1 2 3 4 5 6 7 8 9]
x + 5 =  [ 5  6  7  8  9 10 11 12 13 14]
x - 5 =  [-5 -4 -3 -2 -1  0  1  2  3  4]
x * 2 =  [ 0  2  4  6  8 10 12 14 16 18]
x / 2 =  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
x // 2 =  [0 0 1 1 2 2 3 3 4 4]
-x = [ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
x ** 2 =  [ 0  1  4  9 16 25 36 49 64 81]
x % 2 =  [0 1 0 1 0 1 0 1 0 1]
-((0.5 * x + 1) ** 2)) =  [ -1.    -2.25  -4.    -6.25  -9.   -12.25 -16.   -20.25 -25.   -30.25]
x.add(2) =  [ 2  3  4  5  6  7  8  9 10 11]
abs(xabs) =  [2 1 0 1 2]
Magnitudes are  [5. 5. 2. 1.]


In [130]:
# Numpy's UFuncs - Trigonometric
# define an array of angles starting from 0, 
theta = np.linspace(0, 90, 7)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

invs = [-1, 0, 1]
print("invs = ", invs)
print("arcsin(invs) = ", np.arcsin(invs))
print("arccos(invs) = ", np.arccos(invs))
print("arctan(invs) = ", np.arctan(invs))

theta =  [ 0. 15. 30. 45. 60. 75. 90.]
sin(theta) =  [ 0.          0.65028784 -0.98803162  0.85090352 -0.30481062 -0.38778164
  0.89399666]
cos(theta) =  [ 1.         -0.75968791  0.15425145  0.52532199 -0.95241298  0.92175127
 -0.44807362]
tan(theta) =  [ 0.         -0.8559934  -6.4053312   1.61977519  0.32004039 -0.42070095
 -1.99520041]
invs =  [-1, 0, 1]
arcsin(invs) =  [-1.57079633  0.          1.57079633]
arccos(invs) =  [3.14159265 1.57079633 0.        ]
arctan(invs) =  [-0.78539816  0.          0.78539816]


In [131]:
# exponentials and logarithms
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print("x = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3, x))

x = [1, 2, 4, 10]
print("x = ", x)
print("log x = ", np.log(x))
print("log2(x) = ", np.log2(x))
print("log10(x) = ", np.log10(x))

x =  [1, 2, 3, 4, 5, 6, 7, 8, 9]
e^x =  [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
2^x =  [  2.   4.   8.  16.  32.  64. 128. 256. 512.]
3^x =  [    3     9    27    81   243   729  2187  6561 19683]
x =  [1, 2, 4, 10]
log x =  [0.         0.69314718 1.38629436 2.30258509]
log2(x) =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


In [132]:
x = np.arange(5)
print("x = ", x)
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

x =  [0 1 2 3 4]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [133]:
# Aggregates
x = np.arange(1, 6)
print(x)
print("Sum of elements = ", np.add.reduce(x))
print("Sum of elements = ", np.sum(x)) # equivalent to add.reduce
print("Product of elements = ", np.multiply.reduce(x))
print("Product of elements = ", np.prod(x)) # equivalent to multiply.reduce
print("Store intermediate results of addition = ", np.add.accumulate(x))
print("Store intermediate results of addition = ", np.cumsum(x)) # equivalent to add.accumulate
print("Store intermediate results of multiplication = ", np.multiply.accumulate(x))
print("Store intermediate results of multiplication = ", np.cumprod(x)) # equivalent to multiply.accumulate

[1 2 3 4 5]
Sum of elements =  15
Sum of elements =  15
Product of elements =  120
Product of elements =  120
Store intermediate results of addition =  [ 1  3  6 10 15]
Store intermediate results of addition =  [ 1  3  6 10 15]
Store intermediate results of multiplication =  [  1   2   6  24 120]
Store intermediate results of multiplication =  [  1   2   6  24 120]


In [134]:
# Aggregations: Min, Max, Sum, Product, Median, Quartiles, etc.
L = np.random.random(100)
# python's addition
pySum = sum(L)
print("Python's sum = ", pySum)
# numpy's addition
numPySum = np.sum(L)
print("Numpy's sum = ", numPySum)

# Demo that Numpy's version is faster for huge arrays
L = np.random.random(1000000)
%timeit sum(L)
%timeit np.sum(L)





Python's sum =  52.2044873361121
Numpy's sum =  52.20448733611211
134 ms ± 39 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.22 ms ± 227 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [135]:
# Min, Max functions
x = np.arange(25)
print("x = ", x)

# Python version of min, max
print("Min of array elements = ", min(x))
print("Max of array elements = ", max(x))

# Numpy version of min, max
print("Min of array elements = ", np.min(x))
print("Max of array elements = ", np.max(x))

x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Min of array elements =  0
Max of array elements =  24
Min of array elements =  0
Max of array elements =  24


In [136]:
# Sum, Min, Max on a row or column of a two dimensional grid
grid = np.random.random((3, 4))
print("grid = ", grid)
print("Sum of all elements = ", grid.sum())
print("Sum of elements in 1st column = ", grid.sum(axis=0))
print("Sum of elements in 2nd column = ", grid.sum(axis=1))

print("Min of all elements = ", grid.min())
print("Min of elements in 1st column = ", grid.min(axis=0))
print("Min of elements in 2nd column = ", grid.min(axis=1))

grid =  [[0.7465245  0.53477827 0.90833153 0.24491018]
 [0.7564841  0.34418321 0.22835876 0.23279748]
 [0.8013315  0.20725954 0.81072454 0.79715782]]
Sum of all elements =  6.6128414463277165
Sum of elements in 1st column =  [2.30434011 1.08622102 1.94741484 1.27486548]
Sum of elements in 2nd column =  [2.43454449 1.56182355 2.61647341]
Min of all elements =  0.20725954172329664
Min of elements in 1st column =  [0.7465245  0.20725954 0.22835876 0.23279748]
Min of elements in 2nd column =  [0.24491018 0.22835876 0.20725954]


In [14]:
# Comparison operators as ufuncs
x = np.array([1, 2, 3, 4, 5])
print("Result of x < 3 = ", x < 3)
print("Result of x > 3 = ", x > 3)
print("Result of x <= 3 = ", x <= 3)
print("Result of x >= 3 = ", x >= 3)
print("Result of x == 3 = ", x == 3)
print("Result of x != 3 = ", x != 3)

print("x * 2 = ", x * 2)
print("x ** 2 = ", x ** 2)
print("Result of comparison: ", (x * 2) == (x ** 2))

# Two dimensional example of ufuncs comparison 
#  (demonstrates how can we get boolean values as a result of arithmetic operators
#    and the results can be used to extract nice results as shown in the part - 2)
# part - 1
rng = np.random.RandomState(0)
print(rng)
x = rng.randint(10, size=(3, 4))
print (x)
print ("Result of x < 6: ")
print(x < 6)

# part - 2 (demonstrate how boolean values can be used to arrive at meaningful results)
# how many values less than 6? (1st way)
print("Count of values < 6 = ", np.count_nonzero(x < 6))
# how many values less than 6? (2nd way: true is 1, false is 0 so sum also will get you the result)
print("Count of values < 6 = ", np.sum(x < 6))

# how many values less than 6 in each row?
# we get count of values < 6 in each row
print(np.sum(x < 6, axis=1))

# using any, all, we can quickly checking whether any or all the values are true
# are there any values greater than 8?
np.any(x > 8)

# are there any values less than 0?
np.any(x < 0)

# are all values less than 10?
np.all(x < 10)

# are all values equal to 6?
np.all(x == 6)

# np.all() and np.any() can be used along particular axes as well
# are all values in each row less than 8?
np.all(x < 8, axis=1)

Result of x < 3 =  [ True  True False False False]
Result of x > 3 =  [False False False  True  True]
Result of x <= 3 =  [ True  True  True False False]
Result of x >= 3 =  [False False  True  True  True]
Result of x == 3 =  [False False  True False False]
Result of x != 3 =  [ True  True False  True  True]
x * 2 =  [ 2  4  6  8 10]
x ** 2 =  [ 1  4  9 16 25]
Result of comparison:  [False  True False False False]
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
Result of x < 6: 
[[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]
Count of values < 6 =  8
Count of values < 6 =  8
[4 2 2]


array([ True, False,  True])