In [36]:
import numpy as np

x = np.array([2, 4, 1, 5, 3])
print("Elements of x:")
print(x)

# sort x and copy to y; leave x in tact
y = np.sort(x)
print("Sort x and copy to y (leaving x in tact):")
print(y)
print("Unaffected x:")
print(x)

# in-place sorting of x
print("In-place sorting of x:")
x.sort()
print(x)

# Demo of argsort which returns the indices of elements (not the elements)
y = np.array([2, 4, 1, 5, 3])
print("Elements of y:")
print(y)

ind = np.argsort(y)
print("Indices of elements:")
print(ind)

# Sorting along rows or cols Demo
x = np.random.randint(0, 10, (4, 6))
print("Two dimensional x:")
print(x)

# Sort elements column-wise
np.sort(x, axis=0)

# Demo - Partial Sorts(Partitioning)
# Sometimes we may want only k smallest elements from an array
# np.partition(theArray, k) gives you k smallest values in left partition and remaining elements in the right partition
x = np.array([9, 7, 2, 4, 5, 8, 1, 3])
print("Given x:")
print(x)
print("Show smallest 3 elements in left partition (not necessarily in any order), leaving other in the right partition:")
print(np.partition(x, 3))

# Demo - Sort along specific rows or cols
x = np.random.randint(0, 10, (4, 6))
print("Two dimensional x:")
print(x)

# sort each column of x
print("the first two slots in each row contain the smallest values from that row, with the remaining values filling the remaining slots:")
print(np.partition(x, 2, axis=1))

Elements of x:
[2 4 1 5 3]
Sort x and copy to y (leaving x in tact):
[1 2 3 4 5]
Unaffected x:
[2 4 1 5 3]
In-place sorting of x:
[1 2 3 4 5]
Elements of y:
[2 4 1 5 3]
Indices of elements:
[2 0 4 1 3]
Two dimensional x:
[[9 6 5 5 7 9]
 [3 1 4 8 8 7]
 [6 5 7 0 2 1]
 [2 5 5 7 5 6]]
Given x:
[9 7 2 4 5 8 1 3]
Show smallest 3 elements in left partition (not necessarily in any order), leaving other in the right partition:
[1 3 2 4 5 8 7 9]
Two dimensional x:
[[4 4 0 3 8 6]
 [4 8 0 8 5 1]
 [0 9 8 3 5 3]
 [2 8 7 2 4 1]]
the first two slots in each row contain the smallest values from that row, with the remaining values filling the remaining slots:
[[0 3 4 4 8 6]
 [0 1 4 8 5 8]
 [0 3 3 9 5 8]
 [1 2 2 8 4 7]]
