In [2]:
# This program demonstrates modelling and predicting on breast cancer data using KNN algorithm

import numpy as np
from sklearn import neighbors
from sklearn.model_selection import train_test_split
import pandas as pd

# Data extracted from http://mlr.cs.umass.edu/ml/datasets/Breast+Cancer+Wisconsin+(Original)
# class column conveys if the cancer is benign(=not harmful) or malignant(harmful) 
# indicating with numbers 2 and 4 respectively.
df = pd.read_csv('breast-cancer-wisconsin.csv')
print("Breast Cancer Data:")
df


Breast Cancer Data:


id  clump_thickness  unif_cell_size  unif_cell_shape  marg_adhesion  \
0    1000025                5               1                1              1   
1    1002945                5               4                4              5   
2    1015425                3               1                1              1   
3    1016277                6               8                8              1   
4    1017023                4               1                1              3   
5    1017122                8              10               10              8   
6    1018099                1               1                1              1   
7    1018561                2               1                2              1   
8    1033078                2               1                1              1   
9    1033078                4               2                1              1   
10   1035283                1               1                1              1   
11   1036172                2               1                1              1   
12   1041801                5               3                3              3   
13   1043999                1               1                1              1   
14   1044572                8               7                5             10   
15   1047630                7               4                6              4   
16   1048672                4               1                1              1   
17   1049815                4               1                1              1   
18   1050670               10               7                7              6   
19   1050718                6               1                1              1   
20   1054590                7               3                2             10   
21   1054593               10               5                5              3   
22   1056784                3               1                1              1   
23   1057013                8               4                5              1   
24   1059552                1               1                1              1   
25   1065726                5               2                3              4   
26   1066373                3               2                1              1   
27   1066979                5               1                1              1   
28   1067444                2               1                1              1   
29   1070935                1               1                3              1   
..       ...              ...             ...              ...            ...   
669  1350423                5              10               10              8   
670  1352848                3              10                7              8   
671  1353092                3               2                1              2   
672  1354840                2               1                1              1   
673  1354840                5               3                2              1   
674  1355260                1               1                1              1   
675  1365075                4               1                4              1   
676  1365328                1               1                2              1   
677  1368267                5               1                1              1   
678  1368273                1               1                1              1   
679  1368882                2               1                1              1   
680  1369821               10              10               10             10   
681  1371026                5              10               10             10   
682  1371920                5               1                1              1   
683   466906                1               1                1              1   
684   466906                1               1                1              1   
685   534555                1               1                1              1   
686   536708                1            

### Preprocessing 

In [3]:
# Replace ? with outlier value -99999
df.replace('?', -99999, inplace=True)
print('After replacing ? with outlier value -99999:')
df

After replacing ? with outlier value -99999:


id  clump_thickness  unif_cell_size  unif_cell_shape  marg_adhesion  \
0    1000025                5               1                1              1   
1    1002945                5               4                4              5   
2    1015425                3               1                1              1   
3    1016277                6               8                8              1   
4    1017023                4               1                1              3   
5    1017122                8              10               10              8   
6    1018099                1               1                1              1   
7    1018561                2               1                2              1   
8    1033078                2               1                1              1   
9    1033078                4               2                1              1   
10   1035283                1               1                1              1   
11   1036172                2               1                1              1   
12   1041801                5               3                3              3   
13   1043999                1               1                1              1   
14   1044572                8               7                5             10   
15   1047630                7               4                6              4   
16   1048672                4               1                1              1   
17   1049815                4               1                1              1   
18   1050670               10               7                7              6   
19   1050718                6               1                1              1   
20   1054590                7               3                2             10   
21   1054593               10               5                5              3   
22   1056784                3               1                1              1   
23   1057013                8               4                5              1   
24   1059552                1               1                1              1   
25   1065726                5               2                3              4   
26   1066373                3               2                1              1   
27   1066979                5               1                1              1   
28   1067444                2               1                1              1   
29   1070935                1               1                3              1   
..       ...              ...             ...              ...            ...   
669  1350423                5              10               10              8   
670  1352848                3              10                7              8   
671  1353092                3               2                1              2   
672  1354840                2               1                1              1   
673  1354840                5               3                2              1   
674  1355260                1               1                1              1   
675  1365075                4               1                4              1   
676  1365328                1               1                2              1   
677  1368267                5               1                1              1   
678  1368273                1               1                1              1   
679  1368882                2               1                1              1   
680  1369821               10              10               10             10   
681  1371026                5              10               10             10   
682  1371920                5               1                1              1   
683   466906                1               1                1              1   
684   466906                1               1                1              1   
685   534555                1               1                1              1   
686   536708                1            

In [4]:
# Remove irrelevant column - id, which badly affects the outcome of the KNN, if we retain it
# To test the effect run the program without dropping the id column and notice that the accuracy will be bad
# Dropping id gives an Accuracy =  0.9642857142857143
# Retaining id gives an Accuracy =  0.65
df.drop(['id'], 1, inplace=True) # 2nd parameter indicates whether to remove rows(=0) or cols(=1)
print("After dropping column 'id':")
df

After dropping column 'id':


clump_thickness  unif_cell_size  unif_cell_shape  marg_adhesion  \
0                  5               1                1              1   
1                  5               4                4              5   
2                  3               1                1              1   
3                  6               8                8              1   
4                  4               1                1              3   
5                  8              10               10              8   
6                  1               1                1              1   
7                  2               1                2              1   
8                  2               1                1              1   
9                  4               2                1              1   
10                 1               1                1              1   
11                 2               1                1              1   
12                 5               3                3              3   
13                 1               1                1              1   
14                 8               7                5             10   
15                 7               4                6              4   
16                 4               1                1              1   
17                 4               1                1              1   
18                10               7                7              6   
19                 6               1                1              1   
20                 7               3                2             10   
21                10               5                5              3   
22                 3               1                1              1   
23                 8               4                5              1   
24                 1               1                1              1   
25                 5               2                3              4   
26                 3               2                1              1   
27                 5               1                1              1   
28                 2               1                1              1   
29                 1               1                3              1   
..               ...             ...              ...            ...   
669                5              10               10              8   
670                3              10                7              8   
671                3               2                1              2   
672                2               1                1              1   
673                5               3                2              1   
674                1               1                1              1   
675                4               1                4              1   
676                1               1                2              1   
677                5               1                1              1   
678                1               1                1              1   
679                2               1                1              1   
680               10              10               10             10   
681                5              10               10             10   
682                5               1                1              1   
683                1               1                1              1   
684                1               1                1              1   
685                1               1                1              1   
686                1               1                1              1   
687                3               1                1              1   
688                4               1                1              1   
689                1               1                1              1   
690                1               1                1              3   
691                5              10               10              5   
692                3               1         

In [5]:
# Slice the data into X (=features), y(=label)
# 2nd parameter of drop method indicates whether to remove rows(=0) or cols(=1)
X = np.array(df.drop(['class'], 1)) # Consider all columns as features except 'class'
y = np.array(df['class']) # Consider the column 'class' as it will be our 'Label'

In [6]:
print("Values of X:")
X

Values of X:


array([[5, 1, 1, ..., 3, 1, 1],
       [5, 4, 4, ..., 3, 2, 1],
       [3, 1, 1, ..., 3, 1, 1],
       ...,
       [5, 10, 10, ..., 8, 10, 2],
       [4, 8, 6, ..., 10, 6, 1],
       [4, 8, 8, ..., 10, 4, 1]], dtype=object)

In [7]:
print("Values of y:")
y

Values of y:


array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 2, 4, 4, 4,
       4, 2, 4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4,
       2, 4, 4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2,
       2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2,
       2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 2, 4, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4,

In [10]:
# Split data into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("X_train:")
print(X_train)

print("X_test:")
print(X_test)

print("y_train")
print(y_train)

print("y_test")
print(y_test)

X_train:
[[4 1 1 ... 2 1 1]
 [3 2 1 ... 3 1 1]
 [4 1 1 ... 1 1 1]
 ...
 [8 6 7 ... 3 4 2]
 [3 1 1 ... 2 1 1]
 [3 1 1 ... 1 1 1]]
X_test:
[[4 1 1 ... 1 1 1]
 [6 3 4 ... 3 9 1]
 [5 4 6 ... 8 10 1]
 ...
 [3 3 2 ... 3 6 1]
 [4 7 8 ... 9 1 1]
 [1 1 1 ... 2 1 1]]
y_train
[2 2 2 2 4 2 2 2 4 2 4 4 2 2 2 2 2 4 4 2 2 2 4 2 4 2 2 2 2 2 2 4 4 4 4 2 4
 2 4 2 2 2 4 2 2 4 2 2 2 4 4 4 2 4 4 2 4 4 2 4 2 4 2 2 2 2 2 2 2 2 4 4 2 2
 2 2 2 4 2 4 2 2 2 2 2 2 2 2 4 2 4 2 2 4 4 2 4 2 4 4 4 4 2 2 4 2 2 4 4 4 4
 2 2 2 2 4 4 4 2 4 2 4 2 2 2 2 4 2 2 4 4 2 2 4 4 2 4 2 4 4 2 4 2 4 4 2 2 2
 2 2 2 2 2 4 4 2 2 2 2 2 4 4 2 4 2 4 2 2 2 4 2 2 4 2 2 2 2 2 4 2 4 2 2 2 2
 2 4 2 2 4 2 2 2 4 2 4 2 2 4 2 2 2 2 2 4 2 4 4 2 4 4 2 4 4 2 2 2 4 4 4 2 2
 4 2 2 4 2 2 2 2 4 2 2 2 4 2 2 2 2 4 2 4 4 4 4 2 2 4 2 2 2 2 2 2 2 2 4 2 4
 2 4 2 2 2 2 4 2 4 4 4 4 2 4 2 2 4 2 2 4 2 2 2 2 2 2 2 4 4 2 2 2 2 4 2 2 2
 2 4 2 2 2 2 2 4 2 2 2 2 2 2 2 4 2 4 2 2 4 2 4 2 2 2 4 4 2 4 4 2 4 2 4 2 4
 2 2 4 2 2 2 2 2 4 2 2 2 2 2 2 2 4 2 4 2 4 4 2 2 2 2 2 2 4 

In [11]:
# Select the KNeighbors classifier
clf = neighbors.KNeighborsClassifier()

# Fit the model on training data
clf.fit(X_train, y_train)

accuracy = clf.score(X_test, y_test)
print("Accuracy = ", accuracy)

Accuracy =  0.9928571428571429


In [12]:
# Example demonstration for reshape method that we are about to use
a = np.arange(6) # create single dim array of 6 elements
b = a.reshape(3, 2) # convert single dim array as 3 elements each with 2 elements
print("a:", a)

print("b:")
print(b)

a: [0 1 2 3 4 5]
b:
[[0 1]
 [2 3]
 [4 5]]


In [13]:
# Example demonstration for reshape method that we are about to use
a = np.arange(6) # create single dim array of 6 elements
b = a.reshape(1, -1) # convert single dim array as 3 elements each with 2 elements
print("a:", a)

print("b:")
print(b)

a: [0 1 2 3 4 5]
b:
[[0 1 2 3 4 5]]


In [14]:
# Apply the model on a fictitious sample measure for prediction
ex_measures = np.array([4, 2, 1, 1, 1, 2, 3, 2, 1])
ex_measures = ex_measures.reshape(1, -1) # convert single dim array to two-dim array as our orginal array was two-dim
ex_measures

# Note: We've supplied measures of single patient. 
#      If we have 3 patients, then we will supply the measures as
#   ex_measures = np.array([4, 2, 1, 1, 1, 2, 3, 2, 1], [6, 2, 2, 4, 1, 2, 2, 3, 1], [5, 4, 2, 1, 2, 2, 4, 2, 2])
# and we get result of 3 patient predictions

array([[4, 2, 1, 1, 1, 2, 3, 2, 1]])

In [15]:
prediction = clf.predict(ex_measures)
print("Prediction on example measure = ", prediction)

Prediction on example measure =  [2]


In [19]:
# Let us try with two sets for prediction
ex_measures_set_2 = np.array([[4, 2, 1, 1, 1, 2, 3, 2, 1], [2, 5, 2, 5, 4, 2, 3, 2, 4]])
prediction_2 = clf.predict(ex_measures_set_2)
print("Prediction on example measure = ", prediction_2)

Prediction on example measure =  [2 2]


In [36]:
# Let us try with three sets for prediction
ex_measures_set_3 = np.array([[4, 2, 1, 1, 1, 2, 3, 2, 1], [9, 1, 2, 5, 4, 2, 3, 9, 4], [2, 3, 4, 1, 1, 1, 3, 9, 2]])
prediction_3 = clf.predict(ex_measures_set_3)
print("Prediction on example measure = ", prediction_3)

Prediction on example measure =  [2 4 2]
